export const stocks = {
	AAPL: "Apple Inc.",
	MSFT: "Microsoft Corporation",
	AMZN: "Amazon.com, Inc.",
	GOOGL: "Alphabet Inc. (Class A)",
	GOOG: "Alphabet Inc. (Class C)",
	META: "Meta Platforms, Inc.",
	TSLA: "Tesla, Inc.",
	NVDA: "NVIDIA Corporation",
	PYPL: "PayPal Holdings, Inc.",
	ADBE: "Adobe Inc.",
	CMCSA: "Comcast Corporation",
	NFLX: "Netflix, Inc.",
	PEP: "PepsiCo, Inc.",
	INTC: "Intel Corporation",
	CSCO: "Cisco Systems, Inc.",
	AVGO: "Broadcom Inc.",
	COST: "Costco Wholesale Corporation",
	TMUS: "T-Mobile US, Inc.",
	TXN: "Texas Instruments Incorporated",
	QCOM: "QUALCOMM Incorporated",
	AMGN: "Amgen Inc.",
	SBUX: "Starbucks Corporation",
	CHTR: "Charter Communications, Inc.",
	AMD: "Advanced Micro Devices, Inc.",
	BKNG: "Booking Holdings Inc.",
	MDLZ: "Mondelez International, Inc.",
	ISRG: "Intuitive Surgical, Inc.",
	ADI: "Analog Devices, Inc.",
	MU: "Micron Technology, Inc.",
	GILD: "Gilead Sciences, Inc.",
	ADP: "Automatic Data Processing, Inc.",
	LRCX: "Lam Research Corporation",
	FISV: "Fiserv, Inc.",
	INTU: "Intuit Inc.",
	VRTX: "Vertex Pharmaceuticals Incorporated",
	ATVI: "Activision Blizzard, Inc.",
	REGN: "Regeneron Pharmaceuticals, Inc.",
	JD: "JD.com, Inc.",
	ILMN: "Illumina, Inc.",
	BIDU: "Baidu, Inc.",
	KHC: "The Kraft Heinz Company",
	MAR: "Marriott International, Inc.",
	ROST: "Ross Stores, Inc.",
	MNST: "Monster Beverage Corporation",
	EXC: "Exelon Corporation",
	CSX: "CSX Corporation",
	SIRI: "Sirius XM Holdings Inc.",
	EBAY: "eBay Inc.",
	FAST: "Fastenal Company",
	SNPS: "Synopsys, Inc.",
	WBA: "Walgreens Boots Alliance, Inc.",
	CTSH: "Cognizant Technology Solutions Corporation",
	WDC: "Western Digital Corporation",
	XLNX: "Xilinx, Inc.",
	MCHP: "Microchip Technology Incorporated",
	NTES: "NetEase, Inc.",
	LULU: "Lululemon Athletica Inc.",
	SWKS: "Skyworks Solutions, Inc.",
	ASML: "ASML Holding N.V.",
	ALGN: "Align Technology, Inc.",
	IDXX: "IDEXX Laboratories, Inc.",
	VRSK: "Verisk Analytics, Inc.",
	CDNS: "Cadence Design Systems, Inc.",
	NXPI: "NXP Semiconductors N.V.",
	EA: "Electronic Arts Inc.",
	BMRN: "BioMarin Pharmaceutical Inc.",
	SPLK: "Splunk Inc.",
	INCY: "Incyte Corporation",
	OKTA: "Okta, Inc.",
	CRWD: "CrowdStrike Holdings, Inc.",
	ZM: "Zoom Video Communications, Inc.",
	PTON: "Peloton Interactive, Inc.",
	ROKU: "Roku, Inc.",
	FLEX: "Flex Ltd.",
	AMAT: "Applied Materials, Inc.",
	KLAC: "KLA Corporation",
	LBTYA: "Liberty Global plc",
	EXPE: "Expedia Group, Inc.",
	PCAR: "PACCAR Inc",
	PAYX: "Paychex, Inc.",
	WDAY: "Workday, Inc.",
	CTAS: "Cintas Corporation",
	VRSN: "VeriSign, Inc.",
	NTAP: "NetApp, Inc.",
	CDW: "CDW Corporation",
	TTWO: "Take-Two Interactive Software, Inc.",
	CHKP: "Check Point Software Technologies Ltd.",
	SGEN: "Seagen Inc.",
	DLTR: "Dollar Tree, Inc.",
	MRVL: "Marvell Technology, Inc.",
	BIIB: "Biogen Inc.",
	TTD: "The Trade Desk, Inc.",
	PDD: "Pinduoduo Inc.",
	ZS: "Zscaler, Inc.",
	DOCU: "DocuSign, Inc.",
	SNOW: "Snowflake Inc.",
	PLTR: "Palantir Technologies Inc.",
	TXG: "10x Genomics",
	BYND: "Beyond Meat",
	PSTX: "Poseida Theurapeutics",
	LU: "Lufax Holding Ltd.",
};
