export const stocks = {
	AAPL: "Apple Inc.",
	ABNB: "Airbnb, Inc.	",
	ADBE: "Adobe Inc.",
	ADI: "Analog Devices, Inc.",
	ADP: "Automatic Data Processing, Inc.",
	ADSK: "Autodesk, Inc.",
	AEP: "American Electric Power Company, Inc",
	ALGN: "Align Technology, Inc.",
	AMAT: "Applied Materials, Inc.",
	AMD: "Advanced Micro Devices, Inc.",
	AMGN: "Amgen Inc.",
	AMZN: "Amazon.com, Inc.",
	ANSS: "ANSYS, Inc.",
	ARM: "Arm Holdings ",
	ASML: "ASML Holding N.V.",
	AVGO: "Broadcom Inc.",
	AZN: "AstraZeneca PLC",
	BIDU: "Baidu, Inc.",
	BIIB: "Biogen Inc.",
	BKNG: "Booking Holdings Inc.",
	BKR: "Baker Hughes Company",
	BMRN: "BioMarin Pharmaceutical Inc.",
	BYND: "Beyond Meat, Inc.",
	CCEP: "Coca-Cola Europacific Partners PLC",
	CDNS: "Cadence Design Systems, Inc.",
	CDW: "CDW Corporation",
	CEG: "Constellation Energy Corporation",
	CHKP: "Check Point Software Technologies Ltd.",
	CHTR: "Charter Communications, Inc.",
	CMCSA: "Comcast Corporation",
	COST: "Costco Wholesale Corporation",
	CPRT: "Copart, Inc.",
	CRWD: "CrowdStrike Holdings, Inc.",
	CSCO: "Cisco Systems, Inc.",
	CSGP: "CoStar Group, Inc.",
	CSX: "CSX Corporation",
	CTAS: "Cintas Corporation",
	CTSH: "Cognizant Technology Solutions Corporation",
	DASH: "DoorDash, Inc.",
	DDOG: "Datadog, Inc.",
	DLTR: "Dollar Tree, Inc.",
	DOCU: "DocuSign, Inc.",
	DXCM: "DexCom, Inc",
	EA: "Electronic Arts, Inc.",
	EBAY: "eBay Inc.",
	EXC: "Exelon Corporation",
	EXPE: "Expedia Group, Inc.",
	FANG: "Diamondback Energy, Inc.	",
	FAST: "Fastenal Company",
	FLEX: "Flex Ltd.",
	FTNT: "Fortinet, Inc",
	GEHC: "GE HealthCare Technologies Inc.",
	GFS: "GlobalFoundries Inc",
	GILD: "Gilead Sciences, Inc.",
	GOOGL: "Alphabet Inc. (Class A)",
	GOOG: "Alphabet Inc. (Class C)",
	HON: "Honeywell International Inc",
	IDXX: "IDEXX Laboratories, Inc.",
	ILMN: "Illumina, Inc.",
	INCY: "Incyte Corporation",
	INTC: "Intel Corporation",
	INTU: "Intuit Inc.",
	ISRG: "Intuitive Surgical, Inc.",
	JD: "JD.com, Inc.",
	KDP: "Keurig Dr Pepper Inc",
	KHC: "The Kraft Heinz Company",
	KLAC: "KLA Corporation",
	LBTYA: "Liberty Global plc",
	LRCX: "Lam Research Corporation",
	LULU: "Lululemon Athletica Inc.",
	LU: "Lufax Holding Ltd.",
	MAR: "Marriott International, Inc.",
	MCHP: "Microchip Technology Incorporated",
	MDB: "MongoDB, Inc",
	MDLZ: "Mondelez International, Inc.",
	MELI: "MercadoLibre, Inc.",
	META: "Meta Platforms, Inc.",
	MNST: "Monster Beverage Corporation",
	MRNA: "Moderna, Inc.",
	MRVL: "Marvell Technology, Inc.",
	MSFT: "Microsoft Corporation",
	MU: "Micron Technology, Inc.",
	NFLX: "Netflix, Inc.",
	NTAP: "NetApp, Inc.",
	NTES: "NetEase, Inc.",
	NVDA: "NVIDIA Corporation",
	NXPI: "NXP Semiconductors N.V.",
	ODFL: "Old Dominion Freight Line, Inc",
	OKTA: "Okta, Inc.",
	ON: "ON Semiconductor Corporation",
	ORLY: "O'Reilly Automotive, Inc.",
	PANW: "Palo Alto Networks, Inc.",
	PCAR: "PACCAR Inc",
	PAYX: "Paychex, Inc.",
	PEP: "PepsiCo, Inc.",
	PDD: "Pinduoduo Inc.",
	PLTR: "Palantir Technologies Inc.",
	PTON: "Peloton Interactive, Inc.",
	PYPL: "PayPal Holdings, Inc.",
	QCOM: "QUALCOMM Incorporated",
	REGN: "Regeneron Pharmaceuticals, Inc.",
	ROKU: "Roku, Inc.",
	ROP: "Roper Technologies, Inc",
	ROST: "Ross Stores, Inc.",
	SBUX: "Starbucks Corporation",
	SNOW: "Snowflake Inc.",
	SIRI: "Sirius XM Holdings Inc.",
	SNPS: "Synopsys, Inc.",
	SWKS: "Skyworks Solutions, Inc.",
	TEAM: "Atlassian",
	TMUS: "T-Mobile US, Inc.",
	TSLA: "Tesla, Inc",
	TTD: "The Trade Desk, Inc.",
	TTWO: "Take-Two Interactive Software, Inc.",
	TXG: "10x Genomics, Inc.",
	TXN: "Texas Instruments Incorporated",
	VRSK: "Verisk Analytics, Inc.",
	VRSN: "VeriSign, Inc.",
	VRTX: "Vertex Pharmaceuticals Incorporated",
	WBA: "Walgreens Boots Alliance, Inc.",
	WBD: "Warner Bros. Discovery, Inc",
	WDC: "Western Digital Corporation",
	WDAY: "Workday, Inc.",
	XEL: "Xcel Energy Inc",
	ZM: "Zoom Video Communications, Inc.",
	ZS: "Zscaler, Inc.",
};
