export const stockOptions = [
	{ id: "AAPL", name: "Apple Inc." },
	{ id: "MSFT", name: "Microsoft Corporation" },
	{ id: "AMZN", name: "Amazon.com, Inc." },
	{ id: "GOOGL", name: "Alphabet Inc. (Class A)" },
	{ id: "GOOG", name: "Alphabet Inc. (Class C)" },
	{ id: "META", name: "Meta Platforms, Inc." },
	{ id: "TSLA", name: "Tesla, Inc." },
	{ id: "NVDA", name: "NVIDIA Corporation" },
	{ id: "PYPL", name: "PayPal Holdings, Inc." },
	{ id: "ADBE", name: "Adobe Inc." },
	{ id: "CMCSA", name: "Comcast Corporation" },
	{ id: "NFLX", name: "Netflix, Inc." },
	{ id: "PEP", name: "PepsiCo, Inc." },
	{ id: "INTC", name: "Intel Corporation" },
	{ id: "CSCO", name: "Cisco Systems, Inc." },
	{ id: "AVGO", name: "Broadcom Inc." },
	{ id: "COST", name: "Costco Wholesale Corporation" },
	{ id: "TMUS", name: "T-Mobile US, Inc." },
	{ id: "TXN", name: "Texas Instruments Incorporated" },
	{ id: "QCOM", name: "QUALCOMM Incorporated" },
	{ id: "AMGN", name: "Amgen Inc." },
	{ id: "SBUX", name: "Starbucks Corporation" },
	{ id: "CHTR", name: "Charter Communications, Inc." },
	{ id: "AMD", name: "Advanced Micro Devices, Inc." },
	{ id: "BKNG", name: "Booking Holdings Inc." },
	{ id: "MDLZ", name: "Mondelez International, Inc." },
	{ id: "ISRG", name: "Intuitive Surgical, Inc." },
	{ id: "ADI", name: "Analog Devices, Inc." },
	{ id: "MU", name: "Micron Technology, Inc." },
	{ id: "GILD", name: "Gilead Sciences, Inc." },
	{ id: "ADP", name: "Automatic Data Processing, Inc." },
	{ id: "LRCX", name: "Lam Research Corporation" },
	{ id: "FISV", name: "Fiserv, Inc." },
	{ id: "INTU", name: "Intuit Inc." },
	{ id: "VRTX", name: "Vertex Pharmaceuticals Incorporated" },
	{ id: "ATVI", name: "Activision Blizzard, Inc." },
	{ id: "REGN", name: "Regeneron Pharmaceuticals, Inc." },
	{ id: "JD", name: "JD.com, Inc." },
	{ id: "ILMN", name: "Illumina, Inc." },
	{ id: "BIDU", name: "Baidu, Inc." },
	{ id: "KHC", name: "The Kraft Heinz Company" },
	{ id: "MAR", name: "Marriott International, Inc." },
	{ id: "ROST", name: "Ross Stores, Inc." },
	{ id: "MNST", name: "Monster Beverage Corporation" },
	{ id: "EXC", name: "Exelon Corporation" },
	{ id: "CSX", name: "CSX Corporation" },
	{ id: "SIRI", name: "Sirius XM Holdings Inc." },
	{ id: "EBAY", name: "eBay Inc." },
	{ id: "FAST", name: "Fastenal Company" },
	{ id: "SNPS", name: "Synopsys, Inc." },
	{ id: "WBA", name: "Walgreens Boots Alliance, Inc." },
	{ id: "CTSH", name: "Cognizant Technology Solutions Corporation" },
	{ id: "WDC", name: "Western Digital Corporation" },
	{ id: "XLNX", name: "Xilinx, Inc." },
	{ id: "MCHP", name: "Microchip Technology Incorporated" },
	{ id: "NTES", name: "NetEase, Inc." },
	{ id: "LULU", name: "Lululemon Athletica Inc." },
	{ id: "SWKS", name: "Skyworks Solutions, Inc." },
	{ id: "ASML", name: "ASML Holding N.V." },
	{ id: "ALGN", name: "Align Technology, Inc." },
	{ id: "IDXX", name: "IDEXX Laboratories, Inc." },
	{ id: "VRSK", name: "Verisk Analytics, Inc." },
	{ id: "CDNS", name: "Cadence Design Systems, Inc." },
	{ id: "NXPI", name: "NXP Semiconductors N.V." },
	{ id: "EA", name: "Electronic Arts Inc." },
	{ id: "BMRN", name: "BioMarin Pharmaceutical Inc." },
	{ id: "SPLK", name: "Splunk Inc." },
	{ id: "INCY", name: "Incyte Corporation" },
	{ id: "OKTA", name: "Okta, Inc." },
	{ id: "CRWD", name: "CrowdStrike Holdings, Inc." },
	{ id: "ZM", name: "Zoom Video Communications, Inc." },
	{ id: "PTON", name: "Peloton Interactive, Inc." },
	{ id: "ROKU", name: "Roku, Inc." },
	{ id: "FLEX", name: "Flex Ltd." },
	{ id: "AMAT", name: "Applied Materials, Inc." },
	{ id: "KLAC", name: "KLA Corporation" },
	{ id: "LBTYA", name: "Liberty Global plc" },
	{ id: "EXPE", name: "Expedia Group, Inc." },
	{ id: "PCAR", name: "PACCAR Inc" },
	{ id: "PAYX", name: "Paychex, Inc." },
	{ id: "WDAY", name: "Workday, Inc." },
	{ id: "CTAS", name: "Cintas Corporation" },
	{ id: "VRSN", name: "VeriSign, Inc." },
	{ id: "NTAP", name: "NetApp, Inc." },
	{ id: "CDW", name: "CDW Corporation" },
	{ id: "TTWO", name: "Take-Two Interactive Software, Inc." },
	{ id: "CHKP", name: "Check Point Software Technologies Ltd." },
	{ id: "SGEN", name: "Seagen Inc." },
	{ id: "DLTR", name: "Dollar Tree, Inc." },
	{ id: "MRVL", name: "Marvell Technology, Inc." },
	{ id: "BIIB", name: "Biogen Inc." },
	{ id: "TTD", name: "The Trade Desk, Inc." },
	{ id: "PDD", name: "Pinduoduo Inc." },
	{ id: "ZS", name: "Zscaler, Inc." },
	{ id: "DOCU", name: "DocuSign, Inc." },
	{ id: "SNOW", name: "Snowflake Inc." },
	{ id: "PLTR", name: "Palantir Technologies Inc." },
	{ id: "TXG", name: "10x Genomics" },
	{ id: "BYND", name: "Beyond Meat" },
	{ id: "PSTX", name: "Poseida Theurapeutics" },
	{ id: "LU", name: "Lufax Holding Ltd." },
];
